source "https://rubygems.org"

gem 'brightcontent-core', path: '../core'
gem 'brightcontent-attachments', path: '../attachments'
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'

gemspec
